baseURL = 'https://dongqianyu99.github.io/lee-log/'
languageCode = 'en-us'
title = 'lee-log'
theme = 'not-much'

# [caches]
#   [caches.images]
#     dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
theme = "light"
palette = "lee"
showThemeNotice = false
showPostsSummary = true
math = true

# 文章排序方式：date(日期)、title(标题)、weight(权重) 等
# 可以用 "-" 前缀表示降序，例如 "-date" 表示最新日期在前
mainSections = ["posts"]
paginate = 10

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags"
    weight = 3